### ISSUE TITLE
Quite confused what this application does and how it works. Needs better readme.

### ISSUE THREAD

**Issue by Folaht** [femtopixel/github-release-notifier#9]
I'm looking for an application that checks a github project for new releases every night and if true runs a script. 
This looks like what I'm looking for, but I'm utterly confused how this application is supposed to work and the README jumps ahead of it's introduction and immediately starts talking about how to run it with webhooks, as a cronjob and how to use it with docker.

The only thing I know is that I'm not wanting to use webhooks.

Let's take this example:

```
$ github-release-notifier --package femtopixel/github-release-notifier
{}
```

Curly brackets?

I get the feeling that what's supposed to happen is that this application outputs the version number of the latest release
and then puts that number into ~/.github_release_notifier/versions/team/project.

But alas it doesn't:

```
$ cd ~/.github_release_notifier
-bash: cd: /home/folaht/.github_release_notifier: No file or directory
```

But I can't really tell because I've never succesfully used this application before.

**Comment by jaymoulin** [comment]
> I'm looking for an application that checks a github project for new releases every night and if true runs a script.
You're  ate the right place, this is the exact purpose
> This looks like what I'm looking for, but I'm utterly confused how this application is supposed to work and the README jumps ahead of it's introduction and immediately starts talking about how to run it with webhooks, as a cronjob and how to use it with docker.
> 
> The only thing I know is that I'm not wanting to use webhooks.

Well, this is how I designed it. If you do not want to use webhooks, we'll have to either rewrite everything, either use a middleware that runs your scripts on every webhook (which is the solution I use for some repositories)

> 
> Let's take this example:
> 
> ```
> $ github-release-notifier --package femtopixel/github-release-notifier
> {}
> ```
> 
> Curly brackets?

There is no --package parameter on the default action (which is cron) (cf https://github.com/femtopixel/github-release-notifier/#usage)
You have no result since you didn't configured anything prior running the program. It seems clear enough for me but, you tell me ;) (cf https://github.com/femtopixel/github-release-notifier/#example)

> I get the feeling that what's supposed to happen is that this application outputs the version number of the latest release
> and then puts that number into ~/.github_release_notifier/versions/team/project.
> 
> But alas it doesn't:
> 
> ```
> $ cd ~/.github_release_notifier
> -bash: cd: /home/folaht/.github_release_notifier: No file or directory
> ```
> 
> But I can't really tell because I've never succesfully used this application before.

You're right, it puts the latest version found in the specified `.github_release_notifier/version` file. This file contains a JSON structure on data collected form the differents packages GRN should watch. Also, the file `.github_release_notifier/hooks` whill contain a JSON structure on what package to watch and what webhook to call.

-----

In a nutshell:
1. Specify which package to watch and which script should be called when a new version is released (example `github-release-notifier --action subscribe --webhook https://example.com/updated --package jaymoulin/google-music-manager`)
1. Define the crontab for GRN to go check frequently for new releases (`crontab -l ; echo "0 0 * * * github-release-notifier") | sort - | uniq - | crontab`)
1. Your https://example.com/updated will be called only if a new release exists for the specified package (jaymoulin/google-music-manager in my exemple).  This webhook will receive a JSON structure in its body (example : `{
    "date": [2017, 11, 13, 19, 46, 35, 0, 317, 0],
    "version": "0.7.2",
    "title": "Fixes split modules",
    "content": "",
    "media": "https://avatars0.githubusercontent.com/u/14236493?s=60&v=4",
    "author": "jaymoulin"
    "package_name": "jaymoulin/google-music-manager"
}`)

As README already states, you can configure default path for both versions/hooks JSON structure files with respectively GRN_VERSIONS_FILE/GRN_HOOKS_FILE environment vars (cf. https://github.com/femtopixel/github-release-notifier/#configuration)

**Comment by Folaht** [comment]
Thanks. I get it now. The cron action is to check for new releases and then call all webhooks.
Looks like I will need to fork your project and rewrite it to suit my needs as I need a github-release-source-compiler.

**Comment by jaymoulin** [comment]
As I use GRN to build thing on my side, I already developped that kind of script. You can find a docker image at https://github.com/femtopixel/docker-builder for a plug'n'play Docker image or you can use this script to launch your own script https://github.com/femtopixel/docker-builder/blob/master/daemon.py#L15 (pay attention to the selected line)

As maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, feel free to donate to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).
